version: '3.8'

services:
  # Lägg till:
  postgres:
    image: postgres
    container_name: postgresql-fastapi
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
        - "5432:5432"

  fastapi-app:
    build:
      context: .
    # LÄGG TILL
    depends_on:
      - postgres
    volumes:
      # Mount the local app directory to the /code/app directory in the container    
      - ./app:/code/app
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - MODE
      - DATABASE_URL
      
